# Generated by Django 4.0.6 on 2022-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, to='post.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='followings',
            field=models.ManyToManyField(blank=True, to='post.author'),
        ),
    ]
